### ISSUE TITLE
В единственном числе, с большой буквы

### ISSUE THREAD

**Issue by coursar** [AlekseyNikeshin/Tele2-Tariffs#1]
https://github.com/AlekseyNikeshin/Tele2-Tariffs/blob/b2b38f767bd83f83e27d86321fde53dfbb6c06c9/src/tariffs.java#L1

**Comment by AlekseyNikeshin** [comment]
внес коррективы, через git отправил на репозиторий, прописал пофиксить issue#1 ,но не здесь ничего не изменилось.

**Comment by AlekseyNikeshin** [comment]
Htfrwbz git


C:\Users\Admin\IdeaProjects\Tele2 Tariffs>git add src

C:\Users\Admin\IdeaProjects\Tele2 Tariffs>git commit -m "fixed #1"
[master d774f66] fixed #1
 1 file changed, 3 insertions(+), 3 deletions(-)
 rename src/{tariffs.java => Tariff.java} (61%)
